/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author HP
 */
public class CustomerCheckIn extends javax.swing.JFrame {

    public CustomerCheckIn() {
        initComponents();
        populateCheckInTable();
        setSize(1170, 820);
        setVisible(true);
        jTextField7.setEditable(false);
        jTextField8.setEditable(false);
        SimpleDateFormat myFormat = new SimpleDateFormat("yyyy/MM/dd hh:mm:ss");
        Calendar cal = Calendar.getInstance();  
        jTextField7.setText(myFormat.format(cal.getTime()));
    }
    private String BedType;
    private String RoomType;
    private String RoomNo;
    
    public void RoomDetails(){
        jComboBox4.removeAllItems();
        jTextField8.setText("");
        BedType = (String)jComboBox2.getSelectedItem();
        RoomType = (String)jComboBox3.getSelectedItem();
        try{
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotelmanagementsystem", "root", "SarahQasim123");
        String sql = "SELECT * FROM Room WHERE BedType = ? AND RoomType = ? AND RoomStatus = 'Not Booked'";
        PreparedStatement statement = con.prepareStatement(sql);
        statement.setString(1, BedType);
        statement.setString(2, RoomType);
        ResultSet rs = statement.executeQuery();

            while(rs.next()){
                jComboBox4.addItem(rs.getString(1));
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Customer Check-In");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 30, 911, 43);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 112, 61, 22);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Mobile Number");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(21, 168, 130, 21);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Nationality");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(26, 222, 86, 21);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Gender");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(36, 284, 76, 22);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Email");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(421, 113, 58, 21);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(160, 100, 190, 35);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(160, 160, 190, 33);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(160, 220, 190, 35);

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4);
        jTextField4.setBounds(541, 106, 215, 36);

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5);
        jTextField5.setBounds(541, 161, 215, 36);

        jComboBox1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(160, 280, 190, 35);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("ID Proof");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(413, 168, 81, 21);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Address");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(421, 221, 81, 22);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("Check In Date (TODAY)");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(413, 269, 210, 21);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(541, 216, 215, 35);

        jTextField7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        getContentPane().add(jTextField7);
        jTextField7.setBounds(536, 302, 220, 30);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("Bed Type");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(819, 112, 80, 21);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("Room Type");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(803, 167, 100, 21);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setText("Room Number");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(802, 221, 120, 22);

        jComboBox2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Double", "Triple" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(933, 105, 195, 37);

        jComboBox3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "Not AC" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(933, 160, 197, 36);

        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox4);
        jComboBox4.setBounds(933, 216, 195, 35);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setText("Price");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(821, 288, 43, 21);
        getContentPane().add(jTextField8);
        jTextField8.setBounds(933, 282, 193, 35);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setText("Allot Room");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(263, 716, 151, 53);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(718, 716, 151, 53);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "CutomerID", "Name", "Mobile No", "Nationality", "Gender", "Email", "ID Proof", "Address", "Check-In Date", "Bed Type", "Room Type", "Room No", "Price"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(26, 342, 1115, 340);

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton3.setText("Show Data");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(493, 717, 151, 51);

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(954, 717, 151, 51);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel14.setText("Room Number can not be changed ");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(876, 253, 265, 17);

        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton6.setText("Back");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(63, 716, 121, 53);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WhatsApp Image 2023-06-18 at 18.48.05.jpeg"))); // NOI18N
        jLabel15.setText("jLabel15");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(0, 0, 1170, 780);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String name = jTextField1.getText();
    String mobileNumber = jTextField2.getText();
    String nationality = jTextField3.getText();
    String gender = (String) jComboBox1.getSelectedItem();
    String email = jTextField4.getText();
    String idProof = jTextField5.getText();
    String address = jTextField6.getText();
    String checkInDate = jTextField7.getText();
    String bedType = (String) jComboBox2.getSelectedItem();
    String roomType = (String) jComboBox3.getSelectedItem();
    String roomNumber = (String) jComboBox4.getSelectedItem();
    double price = Double.parseDouble(jTextField8.getText());

    try {
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotelmanagementsystem", "root", "SarahQasim123");
        String checkRoomQuery = "SELECT RoomStatus FROM Room WHERE RoomNo = ?";
        PreparedStatement checkRoomStatement = conn.prepareStatement(checkRoomQuery);
        checkRoomStatement.setString(1, roomNumber);
        ResultSet roomResult = checkRoomStatement.executeQuery();

        if (roomResult.next()) {
            String roomStatus = roomResult.getString("RoomStatus");
            if (roomStatus.equalsIgnoreCase("booked")) {
                JOptionPane.showMessageDialog(this, "This room is already booked.");
                return;
            }
        }

        String updateRoomQuery = "UPDATE Room SET RoomStatus = 'booked' WHERE RoomNo = ?";
        PreparedStatement updateRoomStatement = conn.prepareStatement(updateRoomQuery);
        updateRoomStatement.setString(1, roomNumber);
        updateRoomStatement.executeUpdate();
        String query = "INSERT INTO custcheckin ( name, mobileno, nationality, gender, email, idproof, address, checkindate, bedtype, roomtype, roomno, roomprice) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

        PreparedStatement statement = conn.prepareStatement(query);
        
        statement.setString(1, name);
        statement.setString(2, mobileNumber);
        statement.setString(3, nationality);
        statement.setString(4, gender);
        statement.setString(5, email);
        statement.setString(6, idProof);
        statement.setString(7, address);
        statement.setString(8, checkInDate);
        statement.setString(9, bedType);
        statement.setString(10, roomType);
        statement.setString(11, roomNumber);
        statement.setDouble(12, price);

        int rowsInserted = statement.executeUpdate();

        if (rowsInserted > 0) {
            JOptionPane.showMessageDialog(this, "Room allotted successfully!");
            populateCheckInTable();
        } else {
            JOptionPane.showMessageDialog(this, "Failed to allot room. Please try again.");
        }

        roomResult.close();
        checkRoomStatement.close();
        updateRoomStatement.close();
        statement.close();
        conn.close();
          } 
    catch (SQLException ex) {
        Logger.getLogger(CustomerCheckIn.class.getName()).log(Level.SEVERE, null, ex);
        if (ex.getErrorCode() == 1062) { 
        String errorMessage = ex.getMessage();
        if (errorMessage.contains("Duplicate entry")) {
            JOptionPane.showMessageDialog(this, "This room is already booked.");
        } else 
        {
            JOptionPane.showMessageDialog(this, "Failed to allot room. Please try again.");
        }
    } else 
        {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Failed to connect to the database.");
    }}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
            RoomDetails();
    }//GEN-LAST:event_jComboBox2ActionPerformed
   
    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        RoomDetails();
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        RoomNo=(String)jComboBox4.getSelectedItem();
        
       try{
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotelmanagementsystem", "root", "SarahQasim123");
        String sql = "SELECT * FROM Room WHERE RoomNo = '"+RoomNo+"'";
        PreparedStatement statement = con.prepareStatement(sql);
        ResultSet rs = statement.executeQuery();
            while(rs.next()){
                jTextField8.setText(rs.getString(4));
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        reset();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         int selectedRow = jTable1.getSelectedRow();

    if (selectedRow != -1) {
        jTextField1.setText(jTable1.getValueAt(selectedRow, 1).toString());
        jTextField2.setText(jTable1.getValueAt(selectedRow, 2).toString());
        jTextField3.setText(jTable1.getValueAt(selectedRow, 3).toString());
        jComboBox1.setSelectedItem(jTable1.getValueAt(selectedRow, 4).toString());
        jTextField4.setText(jTable1.getValueAt(selectedRow, 5).toString());
        jTextField5.setText(jTable1.getValueAt(selectedRow, 6).toString());
        jTextField6.setText(jTable1.getValueAt(selectedRow, 7).toString());
        jTextField7.setText(jTable1.getValueAt(selectedRow, 8).toString());
        jComboBox2.setSelectedItem(jTable1.getValueAt(selectedRow, 9).toString());
        jComboBox3.setSelectedItem(jTable1.getValueAt(selectedRow, 10).toString());
        jTextField8.setText(jTable1.getValueAt(selectedRow, 12).toString());      
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    int selectedRow = jTable1.getSelectedRow();


    if (selectedRow != -1) {
        int customerId = Integer.parseInt(jTable1.getValueAt(selectedRow, 0).toString());

        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotelmanagementsystem", "root", "SarahQasim123");
            String deleteQuery = "DELETE FROM custcheckin WHERE customerid = ?";
            PreparedStatement deleteStatement = conn.prepareStatement(deleteQuery);
            deleteStatement.setInt(1, customerId);

            int rowsDeleted = deleteStatement.executeUpdate();

            if (rowsDeleted > 0) {
                JOptionPane.showMessageDialog(this, "Customer entry deleted successfully!");
                reset();
                DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
                tableModel.removeRow(selectedRow);
            } else {
                JOptionPane.showMessageDialog(this, "Failed to delete the customer entry.");
            }

            deleteStatement.close();
            conn.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Failed to connect to the database.");
        }
        }        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Dashboard dashboard = new Dashboard();
       dashboard.setVisible(true);
       dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed
   
    private void populateCheckInTable() {
    DefaultTableModel tableModel = new DefaultTableModel(
        new Object[][]{},
        new String[]{"CustomerID", "Name", "Mobile No", "Nationality", "Gender", "Email", "ID Proof", "Address", "Check-In Date", "Bed Type", "Room Type", "Room No", "Room Price"}
    );
    jTable1.setModel(tableModel);

    try {
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotelmanagementsystem", "root", "SarahQasim123");
        String sql = "SELECT customerid, name, mobileno, nationality, gender, email, idproof, address, checkindate, bedtype, roomtype, roomno, roomprice FROM custcheckin";
        PreparedStatement statement = con.prepareStatement(sql);

        ResultSet resultSet = statement.executeQuery();

        while (resultSet.next()) {
            int customerId = resultSet.getInt("customerid");
            String name = resultSet.getString("name");
            String mobileNumber = resultSet.getString("mobileno");
            String nationality = resultSet.getString("nationality");
            String gender = resultSet.getString("gender");
            String email = resultSet.getString("email");
            String idProof = resultSet.getString("idproof");
            String address = resultSet.getString("address");
            String checkInDate = resultSet.getString("checkindate");
            String bedType = resultSet.getString("bedtype");
            String roomType = resultSet.getString("roomtype");
            String roomNumber = resultSet.getString("roomno");
            double roomPrice = resultSet.getDouble("roomprice");

            tableModel.addRow(new Object[]{customerId, name, mobileNumber, nationality, gender, email, idProof, address, checkInDate, bedType, roomType, roomNumber, roomPrice});
        }

        resultSet.close();
        statement.close();
        con.close();
    } catch (SQLException e) {
        e.printStackTrace();
    }
}
   
    private void reset() {
        jTextField1.setText(""); 
        jTextField2.setText(""); 
        jTextField3.setText(""); 
        jComboBox1.setSelectedIndex(0); 
        jTextField4.setText(""); 
        jTextField5.setText(""); 
        jTextField6.setText(""); 
        jTextField7.setText(""); 
        jComboBox2.setSelectedIndex(0); 
        jComboBox3.setSelectedIndex(0); 
        jComboBox4.setSelectedItem(null); 
        jTextField8.setText(""); 
    }
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CustomerCheckIn CI = new CustomerCheckIn();
                CI.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

                CI.setPreferredSize(new Dimension(1170, 820));

                CI.pack();

                Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
                int screenWidth = screenSize.width;
                int screenHeight = screenSize.height;

                int xPos = (screenWidth - CI.getWidth()) / 2;
                int yPos = (screenHeight - CI.getHeight()) / 2;

                CI.setLocation(xPos, yPos);
                CI.setVisible(true);
                CI.setTitle("Customer Check-In");
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
