import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

public class CustomerCheckout extends javax.swing.JFrame {
    
    public CustomerCheckout() {
        initComponents();
        populateCheckOutTable();
        jTextField1.setEditable(false);
        jTextField2.setEditable(false);
        jTextField3.setEditable(false);
        jTextField4.setEditable(false);
        jTextField5.setEditable(false);
        jTextField6.setEditable(false);
        jTextField7.setEditable(false);
        jTextField8.setEditable(false);
        setSize(1530, 830);
        setVisible(true);
    }
    double totalAmount;
    double pricePerDay;
    private void calculateTotalAmount() {
        try {
            pricePerDay = Double.parseDouble(jTextField2.getText());
            int numberOfDays = Integer.parseInt(jTextField4.getText());

            totalAmount = pricePerDay * numberOfDays;

            jTextField6.setText(String.valueOf(totalAmount));
        } catch (NumberFormatException e) {

            jTextField6.setText("");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        popupMenu1.setLabel("popupMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Customer Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 170, 140, 21);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Price Per Day");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 270, 120, 21);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Check In Date");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(390, 180, 120, 21);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Number of Days Stay");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(390, 260, 180, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Check Out Date(Today)");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(740, 180, 200, 21);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Total Amount");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(772, 263, 120, 22);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(170, 170, 186, 40);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(170, 260, 186, 40);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(520, 170, 190, 36);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(580, 260, 130, 40);

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5);
        jTextField5.setBounds(950, 170, 186, 40);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(950, 250, 186, 40);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText(" Mobile Number");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(1160, 171, 140, 30);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Customer Email");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(1160, 260, 130, 21);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(1310, 160, 185, 40);

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField8);
        jTextField8.setBounds(1310, 250, 185, 40);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("Room Number");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(585, 111, 130, 21);
        getContentPane().add(jTextField9);
        jTextField9.setBounds(730, 107, 203, 31);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(971, 93, 130, 53);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "CustomerID", "Name", "Mobile No", "Nationality", "Gender", "Email", "ID Proof", "Address", "Check-In Date", "Bed Type", "Room Type", "Room Number", "Room Price", "Price Per Day", "Stay Days", "Check-Out-Date", "Total Amount"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 460, 1480, 310);

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton3.setText("Check Out");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(601, 349, 191, 68);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(846, 349, 170, 68);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Customer Check-Out");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(373, 31, 865, 44);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WhatsApp Image 2023-06-18 at 19.34.11.jpeg"))); // NOI18N
        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 0, 1560, 790);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed
    private void populateCheckOutTable() {
        try {
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotelmanagementsystem", "root", "SarahQasim123");

        String selectQuery = "SELECT * FROM CustCheckIn";
        PreparedStatement selectStatement = conn.prepareStatement(selectQuery);
        ResultSet rs = selectStatement.executeQuery();

        String[] columnNames = {"CustomerID", "Name", "Mobile No", "Nationality", "Gender", "Email", "ID Proof", "Address", "Check-In Date", "Bed Type", "Room Type", "Room No", "Room Price", "Price Per Day", "Stay Days", "Check-Out Date", "Total Amount"};
        DefaultTableModel model = new DefaultTableModel(columnNames, 0);

        while (rs.next()) {
            String customerID = rs.getString("CustomerID");
            String name = rs.getString("Name");
            String mobileNo = rs.getString("MobileNo");
            String nationality = rs.getString("Nationality");
            String gender = rs.getString("Gender");
            String email = rs.getString("Email");
            String idProof = rs.getString("IDProof");
            String address = rs.getString("Address");
            String checkInDate = rs.getString("CheckInDate");
            String bedType = rs.getString("BedType");
            String roomType = rs.getString("RoomType");
            String roomNo = rs.getString("RoomNo");
            double roomPrice = rs.getDouble("RoomPrice");
            double pricePerDay = rs.getDouble("PricePerDay");
            int noOfDaysStay = rs.getInt("NoOfDaysStay");
            String checkOutDate = rs.getString("CheckOutDate");
            double totalAmount = rs.getDouble("TotalAmount");
            jTable1.setModel(model);

            Object[] rowData = {customerID, name, mobileNo, nationality, gender, email, idProof, address, checkInDate, bedType, roomType, roomNo, roomPrice, pricePerDay, noOfDaysStay, checkOutDate, totalAmount};
            model.addRow(rowData);
        }
        JTable table = new JTable(model);
        conn.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String roomNo = jTextField9.getText();

        if (roomNo != null && !roomNo.isEmpty()) {
            try {
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotelmanagementsystem", "root", "SarahQasim123");

                String selectQuery = "SELECT Name, MobileNo, Email, CheckInDate FROM CustCheckIn WHERE RoomNo = ?";
                PreparedStatement selectStatement = conn.prepareStatement(selectQuery);
                selectStatement.setString(1, roomNo);

                ResultSet rs = selectStatement.executeQuery();

                if (rs.next()) {
                    jTextField9.setEditable(false);
                    jTextField1.setText(rs.getString("Name"));
                    jTextField7.setText(rs.getString("MobileNo"));
                    jTextField8.setText(rs.getString("Email"));
                    jTextField2.setText(getRoomPrice(roomNo));

                    SimpleDateFormat myFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
                    Calendar cal = Calendar.getInstance();
                    String checkOutDateString = myFormat.format(cal.getTime());
                    jTextField5.setText(checkOutDateString);

                    String checkInDateString = rs.getString("CheckInDate");
                    jTextField3.setText(checkInDateString);
                    java.util.Date checkInDate = myFormat.parse(checkInDateString);
                    java.util.Date checkOutDate = myFormat.parse(checkOutDateString);

                    long difference = checkOutDate.getTime() - checkInDate.getTime();
                    int noOfDaysStay = (int) (difference / (1000 * 60 * 60 * 24));    
                    jTextField4.setText(String.valueOf(noOfDaysStay));

                    String roomPrice = getRoomPrice(roomNo);
                    if (roomPrice != null) {
                        double pricePerDay = Double.parseDouble(roomPrice);
                        double totalAmount = pricePerDay * noOfDaysStay;
                        jTextField6.setText(String.valueOf(totalAmount));
                    } else 
                    {
                        jTextField6.setText("");
                    }
                } else 
                {
                    JOptionPane.showMessageDialog(null, "Room Number is not booked or does not exist.");
                }
                
                conn.close();
            } catch (Exception e) 
            {
                JOptionPane.showMessageDialog(null, e);
            }
        } else 
        {
            JOptionPane.showMessageDialog(null, "Room Number is empty or not entered.");
        }
    }

    private String getRoomPrice(String roomNo) throws SQLException {
        String roomPrice = null;

        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotelmanagementsystem", "root", "SarahQasim123");

        String selectQuery = "SELECT RoomPrice FROM Room WHERE RoomNo = ?";
        PreparedStatement selectStatement = conn.prepareStatement(selectQuery);
        selectStatement.setString(1, roomNo);

        ResultSet rs = selectStatement.executeQuery();

        if (rs.next()) {
            roomPrice = rs.getString("RoomPrice");
        }
        conn.close();
        return roomPrice;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String roomNo = jTextField9.getText();

        if (roomNo != null && !roomNo.isEmpty()) {
            try {
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotelmanagementsystem", "root", "SarahQasim123");

                SimpleDateFormat myFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
                Calendar cal = Calendar.getInstance();
                String checkOutDateString = myFormat.format(cal.getTime());

                int noOfDaysStay = Integer.parseInt(jTextField4.getText());
                double totalAmount = Double.parseDouble(jTextField6.getText());
                double pricePerDay = Double.parseDouble(jTextField2.getText());

                // Update the CustCheckIn table with checkout information
                String updateQuery = "UPDATE CustCheckIn SET PricePerDay = ?, CheckOutDate = ?, NoOfDaysStay = ?, TotalAmount = ? WHERE RoomNo = ?";
                PreparedStatement updateStatement = conn.prepareStatement(updateQuery);
                updateStatement.setDouble(1, pricePerDay);
                updateStatement.setString(2, checkOutDateString);
                updateStatement.setInt(3, noOfDaysStay);
                updateStatement.setDouble(4, totalAmount);
                updateStatement.setString(5, roomNo);

                updateStatement.executeUpdate();

                JOptionPane.showMessageDialog(null, "Information saved successfully.");

                int rowCount = jTable1.getRowCount();
            for (int i = 0; i < rowCount; i++) {
                String tableRoomNo = jTable1.getValueAt(i, 11).toString();
                if (tableRoomNo.equals(roomNo)) {
                    jTable1.setValueAt(pricePerDay, i, 12);
                    jTable1.setValueAt(noOfDaysStay, i, 14);
                    jTable1.setValueAt(checkOutDateString, i, 15);
                    jTable1.setValueAt(totalAmount, i, 16);
                    break;
                }
            }
                conn.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Room Number is empty or not entered.");
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Dashboard dashboard = new Dashboard();
       dashboard.setVisible(true);
       dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerCheckout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CustomerCheckout CO = new CustomerCheckout();
                CO.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

                CO.setPreferredSize(new Dimension(1530, 830));

                CO.pack();

                Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
                int screenWidth = screenSize.width;
                int screenHeight = screenSize.height;

                int xPos = (screenWidth - CO.getWidth()) / 2;
                int yPos = (screenHeight - CO.getHeight()) / 2;

                CO.setLocation(xPos, yPos);
                CO.setVisible(true);
                CO.setTitle("Customer Check-Out");
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private java.awt.PopupMenu popupMenu1;
    // End of variables declaration//GEN-END:variables
}
