
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.*;
import java.awt.*;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

public class MainForm extends javax.swing.JFrame {

    public MainForm() {
        initComponents();
        addComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // </editor-fold>
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Next = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(398, 500));
        getContentPane().setLayout(null);

        Next.setBackground(new java.awt.Color(238, 222, 173));
        Next.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        Next.setText("Next");
        Next.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextActionPerformed(evt);
            }
        });
        getContentPane().add(Next);
        Next.setBounds(1020, 580, 140, 60);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WhatsApp Image 2023-06-18 at 16.22.22.jpeg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1200, 670);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextActionPerformed
        GUISignIn signinForm = new GUISignIn();
        signinForm.setVisible(true);   
        dispose();
    }//GEN-LAST:event_NextActionPerformed

    /**
     * @param args the command line arguments
     */
        private void addComponents() {
        // Create a layered pane
        JLayeredPane layeredPane = new JLayeredPane();
        layeredPane.setPreferredSize(new Dimension(1050, 900));

        // Create the image label
        JLabel imageLabel = new JLabel(new ImageIcon("C:\\Users\\HP\\Downloads\\WhatsApp Image 2023-06-16 at 16.50.54.jpeg"));
        imageLabel.setBounds(0, 0, 1300, 730);
        layeredPane.add(imageLabel, JLayeredPane.DEFAULT_LAYER);

        // Create the button
        JButton button = new JButton("Click me!");
        button.setBounds(10, 10, 100, 30);
        layeredPane.add(button, JLayeredPane.PALETTE_LAYER);

        // Add the layered pane to the frame's content pane
        getContentPane().add(layeredPane);
    }
        
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            SwingUtilities.invokeLater(() -> {   
            MainForm mainForm = new MainForm();
            mainForm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

            mainForm.setPreferredSize(new Dimension(1200, 700));

            mainForm.pack();

            Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
            int screenWidth = screenSize.width;
            int screenHeight = screenSize.height;

            int xPos = (screenWidth - mainForm.getWidth()) / 2;
            int yPos = (screenHeight - mainForm.getHeight()) / 2;

            mainForm.setLocation(xPos, yPos);
            mainForm.setVisible(true);
            mainForm.setSize(1200, 700);
            mainForm.setTitle("Hotel Management System");
        });
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Next;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
